name: CI

on:
  push:
    branches:
      - main
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Install luacheck
        run: sudo apt-get install -y luacheck

      - name: Install stylua
        run: |
          curl -sL https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux-x86_64.zip -o stylua.zip
          unzip -q stylua.zip
          sudo mv stylua /usr/local/bin/stylua

      - name: Lint
        run: make lint

      - name: Format
        run: make format && git diff --exit-code

      - name: Test
        run: make test
